# Creating Arrays

In [1]:
import numpy as np
np.__version__
#integer array

np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [2]:
# fixed datatype array
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [3]:
#MultiDimensional Array
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
# Array of zeors
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#Array of a fixed value (Multi)
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
#array of a sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
#Evenly distributed values array in a range
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
#Array of normally distributed random values
np.random.normal(0,1,(3,3))

array([[-0.97415478, -1.52412257,  0.03439322],
       [-0.77357186, -0.15977901,  0.62695874],
       [ 1.67936112, -0.03845619, -1.44547248]])

In [9]:
#Random values in a range
np.random.randint(0,10,(3,3))

array([[7, 5, 2],
       [0, 1, 8],
       [2, 4, 0]])

In [10]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

# Numpy array attributes

In [12]:
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))
print(x3.size)
print(x3.shape)
print(x3.ndim)

60
(3, 4, 5)
3


In [13]:
x3.dtype

dtype('int32')

In [14]:
x3.itemsize

4

In [15]:
x3.nbytes

240

# Array indexing



In [16]:
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
#access single element
x1[0]

5

In [18]:
#Negative index from the last
x1[-1]

9

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
#Multi dimensional array
x2[0,0]

3

In [21]:
#Negative indexing in multidimensional arrays
x2[0,-1]

4

In [22]:
#Modify values
x2[0,0]=2
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# Array slicing
 X[start:stop:steps]

In [23]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [25]:
#elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [26]:
#middle subraay
x[4:7]

array([4, 5, 6])

In [27]:
#Every element in a sequence
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
#All element revers
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
 #reverse from inex 5
x[4::-1]

array([4, 3, 2, 1, 0])

In [30]:
#Multidimensional subarray
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [37]:
#2 rows 3 column
x2[:2,:3]

array([[2, 5, 2],
       [7, 6, 8]])

In [44]:
#All rows every even column
x2[:,::2]

array([[2, 2],
       [7, 8],
       [1, 7]])

In [45]:
#Reverse subaarray dimension`
x2[::-1,::-1]


array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 2]])

In [47]:
#single element in multidimensional array
x2[:,0]  #first colum
x2[0,:]  #first nrow 

array([2, 5, 2, 4])

In [48]:
#subarray no copy view in numpy
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [51]:
x2_sub=x2[:2,:2]
x2_sub

array([[2, 5],
       [7, 6]])

In [52]:
x2_sub[0,0]=99
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [54]:
#subarray copy 
x2_sub_copy=x2[:2,:2].copy()
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [55]:
x2_sub_copy[0,0]=42

In [56]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Reshaping array

In [58]:
grid=np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [61]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [62]:
#new axis row
x[np.newaxis,:]

array([[1, 2, 3]])

In [63]:
#new axis columkn
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Arrray concatation and spliting 

In [69]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.array([1,2,3,3,2,1])

In [67]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [70]:
#concate More than two arrays 
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 1, 2, 3, 3, 2, 1])

In [74]:
#Two dimensional concate
grid=np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [82]:
#horizontal and virtical stack
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [85]:
np.hstack([x,x])   #all arrays must have same dimension

array([1, 2, 3, 1, 2, 3])

In [86]:
#splitting
?np.split